from utils.datadict import DataDictionnary

PIR_CONDITIONS = DataDictionnary({'Name' : None, 'Amount' : None, 'Unit': None, 'PerUnit' : None, 'UOM': None})

        
DEFAULT_PIR = DataDictionnary({"1st Rem./Exped" : None,
                                "2nd Rem./Exped" : None,
                                "3rd Rem./Exped": None,
                                "Vendor Mat. No." : None, 
                                "Vendor Subrange" : None, 
                                "VSR Sort No." : None, 
                                "Vendor Mat. GRP" : None, 
                                "Points" : None, 
                                "Salesperson" : None, 
                                "Telephone" : None, 
                                "Return Agmt" : None, 
                                "Prior Vendor" : None,
                                "Order Unit" : "EA",
                                "Conversion 1": 1,
                                "Conversion 2": 1,
                                "Var Order Unit" : 1,
                                "Certif Date" : None,
                                "Certificate" : None,
                                "Valid to" : None,
                                "Ctry of Origin" : None,
                                "Region" : None,
                                "Number" : None,
                                "Manufacturer" : None,
                                "Available from" : None,
                                "Available to": None,
                                "Regular Vendor": False,
                                "Plann Del Time" : 1,
                                "Purch. Group" : None,
                                "Standard Qty" : 1, 
                                "Minimum Qty" : None, 
                                "Rem Shelf Life" : None, 
                                "Shipping Instr." : None, 
                                "Max. Quantity" : None, 
                                "Tol. Underdl." : None, 
                                "Tol. Overdl." : None, 
                                "Unlimited Box" : False, 
                                "GR-Bsd IV Box" : False,
                                "No ERS Box" : False,
                                "No MText" : False,
                                "Ackn. Rqd" : False,
                                "Conf. Ctrl" : None,
                                "Tax Code" : None,
                                "Procedure" : None,
                                "Rndg Prof." : None,
                                "UoM Group" : None,
                                "RMA Req." : None,
                                "Net Price" : 1,
                                "Net Price Currency": None,
                                "Per Unit": None,
                                "Net Price UOM": None,
                                "Qty Conv. 1": None,
                                "Qty Conv. 2" : None,
                                "PR Date Cat" : None,
                                "Incoterms 1" : None,
                                "Incoterms 2" : None,
                                "No Cash Disc. Box" : False,
                                "Cond Grp" : None,
                                "Valid From": None,
                                "Valid To": None,
                                "Condition Dict" : [PIR_CONDITIONS]})


DEFAULT_SL = DataDictionnary({"Valid From" : "26.02.2019",
                              "Valid To" : "31.12.9999",
                              "Vendor": None,
                              "POrg": None,
                              "Vendor Plant" : None,
                              "Unit": None,
                              "Agreement Nb" : None,
                              "Agreement Item" : '0',
                              "Fixed" : False,
                              "Blocked" : False,
                              "MRP" : None})



